#cloud-config
local-hostname: ${var.vm-name-prefix}-${count.index}.${var.domain}${count.index}
instance-id: ${var.vm-name-prefix}-${count.index}.${var.domain}${count.index}.com
network:
  version: 2
  ethernets:
    ens192:
      dhcp4: false
      addresses:
        - ${var.ipv4_address}.$[count.index].5/${var.ipv4_netmask}
      gateway4: ${var.ipv4_gateway}.$[count.index].1
      nameservers:
        search: ${var.domain}${count.index}.com
        addresses: ${var.dns_server}
growpart:
  mode: auto
  devices: ['/dev/sda2']
  ignore_growroot_disabled: true
wait-on-network:
  ipv4: true
